version: "3.7"


services:

  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rezy/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./Dockerized/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network


  #Nginx
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./Dockerized/nginx/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./Dockerized/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    db_data:
        driver: local
